ingressService:
  name: ingress-server-latest
  configuration:
    s3:
      storeUrl: "s3://app-databuk-test-service/bukov-main.zarr"
  service:
    name: ingress-server-latest
  ingress:
    hosts:
      - name: zarr-fuse-ingress-server-latest.dyn.cloud.e-infra.cz
        tls:
          enabled: true
          secretName: zarr-fuse-ingress-server-latest-dyn-cloud-e-infra-cz-tls
airflow:
  ingress:
    web:
      hosts:
        - name: "zarr-fuse-extractor-service-latest.dyn.cloud.e-infra.cz"
          tls:
            enabled: true
            secretName: "zarr-fuse-extractor-service-latest-dyn-cloud-e-infra-cz-tls"
