ingressService:
  name: ingress-server
  configuration:
    s3:
      storeUrl: "s3://app-databuk-release-service/bukov.zarr"
  service:
    name: ingress-server
  ingress:
    hosts:
      - name: zarr-fuse-ingress-server.dyn.cloud.e-infra.cz
        tls:
          enabled: true
          secretName: zarr-fuse-ingress-server-dyn-cloud-e-infra-cz-tls
airflow:
  ingress:
    web:
      hosts:
        - name: "zarr-fuse-extractor-service.dyn.cloud.e-infra.cz"
          tls:
            enabled: true
            secretName: "zarr-fuse-extractor-service-dyn-cloud-e-infra-cz-tls"
