endpoints:
  - name: weather
    endpoint: /api/v1/weather
    schema_path: schemes/weather_scheme_v1.yaml
  - name: sensors
    endpoint: /api/v1/sensors
    schema_path: schemes/sensors_scheme_v1.yaml
  - name: tree
    endpoint: /api/v1/tree
    schema_path: schemes/tree_scheme_v1.yaml
