apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingress-server
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  selector:
    matchLabels:
      app: ingress-server
  template:
    metadata:
      labels:
        app: ingress-server
    spec:
      securityContext:
        {{- toYaml .Values.securityContext.pod | nindent 8 }}
      containers:
        - name: ingress-server
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: Always
          ports:
            - name: {{ .Values.service.internalPort.name | quote }}
              containerPort: {{ .Values.service.internalPort.port | int }}
          env:
            - name: S3_ACCESS_KEY
              value: {{ .Values.deployment.secrets.s3.accessKey | quote }}
            - name: S3_SECRET_KEY
              value: {{ .Values.deployment.secrets.s3.secretKey | quote }}
          startupProbe:
            httpGet:
              path: /
              port: http
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 36
          livenessProbe:
            httpGet:
              path: /
              port: http
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 2
          readinessProbe:
            httpGet:
              path: /
              port: http
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 2
          securityContext:
            {{- toYaml .Values.securityContext.container | nindent 12 }}
