apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: zarr-fuse-ingress-server
  ports:
    - name: {{ .Values.service.externalPort.name | quote }}
      port: {{ .Values.service.externalPort.port | int }}
      targetPort: {{ .Values.service.internalPort.name | quote }}
