apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}
  labels:
    app.kubernetes.io/name: {{ .Values.app.name }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ .Values.app.name }}
  ports:
    - name: {{ .Values.service.externalPort.name | quote }}
      port: {{ .Values.service.externalPort.number | int }}
      targetPort: {{ .Values.service.internalPort.name | quote }}
