image:
  repository: docker.io/mocstepan/zarr-fuse-ingress-server
  tag: "latest"

deployment:
  name: ingress-server
  replicaCount: 1
  secrets:
    s3:
      accessKey: ""
      secretKey: ""
    basicAuth:
      usersJson: "{}"

service:
  name: ingress-server-service
  type: ClusterIP
  externalPort:
    number: 80
    name: http
  internalPort:
    number: 8000
    name: http

ingress:
  className: "nginx"
  annotations: {}
  hosts:
    - host: zarr-fuse-ingress-server.dyn.cloud.e-infra.cz
      paths:
        - path: /
          pathType: Prefix # ImplementationSpecific
  tls:
    - secretName: zarr-fuse-ingress-server-dyn-cloud-e-infra-cz-tls
      hosts:
        - zarr-fuse-ingress-server.dyn.cloud.e-infra.cz

resources: {}

securityContext:
  pod:
    fsGroup: 11233
    runAsNonRoot: true
    runAsUser: 11233
    runAsGroup: 11233
    seccompProfile:
      type: RuntimeDefault
  container:
    capabilities:
      drop:
        - ALL
    allowPrivilegeEscalation: false
    privileged: false
    runAsNonRoot: true
    readOnlyRootFilesystem: true
    runAsUser: 11233
    runAsGroup: 11233
