image:
  repository: mocstepan/zarr-fuse-ingress-server
  tag: "latest"

deployment:
  name: zarr-fuse-ingress-server
  replicaCount: 1
  secrets:
    s3:
      accessKey: ""
      secretKey: ""

service:
  name: ingress-server-service
  type: ClusterIP
  externalPort:
    port: 80
    name: http
  internalPort:
    port: 8000
    name: http

ingress:
  className: "nginx"
  annotations: {}
  hosts:
    - host: zarr-fuse-ingress-server.dyn.cloud.e-infra.cz
      paths:
        - path: /
          pathType: Prefix # ImplementationSpecific
  tls:
    - secretName: zarr-fuse-ingress-server.dyn.cloud.e-infra.cz
      hosts:
        - zarr-fuse-ingress-server-dyn-cloud-e-infra-cz-tls

resources:
  requests:
    cpu: 500m
    memory: 2048Mi
  limits:
    cpu: 1000m
    memory: 4096Mi

# Security: container runs as non-root user 11233 (matches your Dockerfile)
securityContext:
  pod:
    runAsNonRoot: true
    runAsUser: 11233
    runAsGroup: 11233
    fsGroup: 11233
  container:
    runAsNonRoot: true
    runAsUser: 11233
