FROM docker.io/library/python:3.11-slim-bullseye

ARG APP_VERSION="devel"

ARG zarr_fuse_branch="main"
ARG git_version="1:2.30.2-1+deb11u5"
ARG waitress_version="3.0.2"

LABEL org.opencontainers.image.title="ZarrFuse Ingress (Backend-only)"
LABEL org.opencontainers.image.description="Flask service for CSV/JSON ingestion into an S3-backed Zarr store (no UI)."
LABEL org.opencontainers.image.version="${APP_VERSION}"
LABEL org.opencontainers.image.licenses="BSD-3-Clause"
LABEL org.opencontainers.image.source="https://github.com/geomop/zarr_fuse"
LABEL org.opencontainers.image.url="https://github.com/geomop/zarr_fuse"
LABEL org.opencontainers.image.authors="Geomop / Stepan Moc <stepan.mocik@gmail.com>"
LABEL maintainer="Geomop / Stepan Moc <stepan.mocik@gmail.com>"

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV PIP_NO_CACHE_DIR=1
ENV AWS_REQUEST_CHECKSUM_CALCULATION=when_required
ENV AWS_RESPONSE_CHECKSUM_VALIDATION=when_required

RUN groupadd -r ingress && useradd -r -g ingress -u 11233 -m -d /ingress-server ingress && \
    apt-get update && apt-get install -y --no-install-recommends git=${git_version} && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir "git+https://github.com/GeoMop/zarr_fuse.git@${zarr_fuse_branch}" && \
    pip install --no-cache-dir waitress==${waitress_version}

# --- Install ingress server ---
WORKDIR /ingress-server

COPY --chown=ingress:ingress pyproject.toml ingress_server/ inputs/ ./
COPY --chown=ingress:ingress oci/install_extractor_dependencies.sh ./scripts/install_extractor_dependencies.sh

RUN pip install --no-cache-dir .

RUN  chmod +x ./scripts/install_extractor_dependencies.sh && \
    ./scripts/install_extractor_dependencies.sh

ENV CONFIG_DIR_PATH="/ingress-server/inputs"

USER ingress
EXPOSE 8000

CMD ["waitress-serve", "--host", "0.0.0.0", "--port", "8000", "--call", "ingress_server.main:create_app_with_worker"]
