endpoints:
  - name: bukov
    endpoint: /api/v1/bukov
    schema_path: schemas/bukov_schema_v1.yaml

active_scrappers:
  - name: bukov-scraper
    cron: "0 3 * * *"
    url: "http://bukov.scraper/api/v1/scrape"
    schema_path: schemas/bukov_schema_v1.yaml
