endpoints:
  - name: bukov
    endpoint: /api/v1/bukov
    schema_path: schemas/bukov_schema_v1.yaml
    extract_fn: normalize_new # fn(json_data, meta_data) -> pd.DataFrame
    fn_module: inputs.extract.bukov_extract
# active_scrappers:
#   - name: bukov-scraper
#     cron: "*/1 * * * *"
#     url: "https://api.restful-api.dev/objects/7"
#     schema_path: bukov_schema_v1.yaml
#     method: GET
