name: Helm Lint
description: Lint a Helm chart
inputs:
  working-directory:
    description: The working directory to run the action in
    required: true
  chart:
    description: Path to the Helm chart to lint
    required: false
    default: .
  values:
    description: Additional values to pass to helm lint command
    required: false
    default: ""
  helm-dependencies:
    description: "Comma-separated list of Helm repositories to add before linting. Format: name=url"
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - name: Add required Helm repositories
      shell: bash
      if: ${{ inputs.helm-dependencies }}
      run: |
        for repo in $(echo "${{ inputs.helm-dependencies }}" | tr "," "\n"); do
          name=$(echo "$repo" | cut -d'=' -f1)
          url=$(echo "$repo" | cut -d'=' -f2)
          helm repo add "$name" "$url"
        done
    - name: Build chart dependencies
      shell: bash
      if: ${{ inputs.helm-dependencies }}
      working-directory: ${{ inputs.working-directory }}
      run: helm dependency build ${{ inputs.chart }}
    - name: Lint helm chart
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: helm lint ${{ inputs.chart }} --strict ${{ inputs.values }}
    - name: Template helm chart
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: helm template chart ${{ inputs.chart }} ${{ inputs.values }} > /dev/null
