name: Helm Lint
description: Lint a Helm chart
inputs:
  chart-path:
    description: Path to the Helm chart to lint
    required: false
    default: .
  values:
    description: Additional values to pass to helm lint command
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - name: Lint helm chart
      shell: bash
      run: helm lint --strict {{ inputs.values }} > /dev/null
    - name: Template helm chart
      shell: bash
      run: helm template chart {{ inputs.chart-path }} {{ inputs.values }} > /dev/null
