endpoints:
  - name: weather
    endpoint: /api/v1/weather
    schema_path: schemas/weather_schema_v1.yaml
  - name: sensor
    endpoint: /api/v1/sensor
    schema_path: schemas/sensor_schema_v1.yaml
  - name: tree
    endpoint: /api/v1/tree
    schema_path: schemas/tree_schema_v1.yaml
