endpoints:
  - name: sensor
    endpoint: /api/v1/sensor
    schema_path: schemas/prod/prod_sensor_schema_v1.yaml
  - name: tree
    endpoint: /api/v1/tree
    schema_path: schemas/prod/prod_tree_schema_v1.yaml
  - name: weather
    endpoint: /api/v1/weather
    schema_path: schemas/prod/prod_weather_schema_v1.yaml
