apiVersion: v2
name: ingress-server
description: Backend-only Flask ingress to upload CSV/JSON into an S3-backed Zarr store
type: application
version: 0.1.0
appVersion: "0.2.0"
home: https://github.com/geomop/zarr_fuse
sources:
  - https://github.com/geomop/zarr_fuse
maintainers:
  - name: Stepan Moc
    email: stepan.mocik@gmail.com
