name: Zarr-Fuse Tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      max-parallel: 1   # Avoid race condition for the single test S3 storage bucket. 
      matrix:
        python-version: [ "3.11", "3.12", "3.13"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install package
      run: |
        python -m pip install --upgrade pip
        pip install tox

    - name: Test with tox
      run: tox
